[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "plox"
version = '0.1.0'
requires-python = ">= 3.12"
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest"
]
